[server]
headless = true
enableCORS = false
port = $PORT

[global]
environment = "development"

[deprecation]
showfileUploaderEncoding = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
fastReruns = true

[jvm]
path = "/usr/lib/jvm/java-11-openjdk-amd64"

[server]
headless = true
enableCORS = false
port = $PORT